using System;
using UnityEngine;

namespace PowerCellStudio
{
    /// <summary>
    /// 中文: 可序列化的动作片段基类，表示时间轴上的一个片段。
    /// English: Serializable base class for an action clip, representing a segment on a timeline.
    /// </summary>
    [Serializable]
    public abstract class ActClipData
    {
        /// <summary>
        /// 中文: 唯一标识符，默认使用 Guid 生成。
        /// English: Unique identifier, generated by Guid by default.
        /// </summary>
        public string id = Guid.NewGuid().ToString();

        /// <summary>
        /// 中文: 片段在时间轴上的起始时间（秒）。
        /// English: Start time of the clip on the timeline (in seconds).
        /// </summary>
        public float start = 0f;

        /// <summary>
        /// 中文: 片段持续时长（秒）。
        /// English: Duration length of the clip (in seconds).
        /// </summary>
        public float length = 1f;

        /// <summary>
        /// 中文: 片段结束时间（start + length）。
        /// English: End time of the clip (start + length).
        /// </summary>
        public float duration => start + length;

        /// <summary>
        /// 中文: 根据给定时间计算标准化进度（0 到 1），并进行裁剪。
        /// English: Calculate normalized progress (0 to 1) for a given time and clamp the result.
        /// </summary>
        /// <param name="time">中文: 目标时间（秒）。English: Target time (seconds).</param>
        /// <returns>中文: 标准化的时间值（0 到 1）。English: Normalized time value (0 to 1).</returns>
        protected float GetNormalizedTime(float time) => Mathf.Clamp01((time - start) / length);

        /// <summary>
        /// 中文: 获取片段相对于起始点的经过时间，并裁剪在 [0, length] 范围内。
        /// English: Get the elapsed time relative to the clip's start and clamp to [0, length].
        /// </summary>
        /// <param name="time">中文: 目标时间（秒）。English: Target time (seconds).</param>
        /// <returns>中文: 裁剪后的经过时间（秒）。English: Clamped elapsed time (seconds).</returns>
        protected float GetProcessTime(float time) => Mathf.Clamp(time - start, 0f, length);

        /// <summary>
        /// 中文: 上一次模拟所使用的时间，用于判断片段开始/结束回调的触发。
        /// English: The time used in the last simulation step, used to determine start/end callback triggers.
        /// </summary>
        protected float lastTime;

        /// <summary>
        /// 中文: 在指定时间对该片段进行仿真执行，包含开始、进行、结束时的回调逻辑。
        /// English: Simulate this clip at the specified time, handling start/ongoing/end callbacks.
        /// </summary>
        /// <param name="target">中文: 运行时播放器目标。English: Runtime player target.</param>
        /// <param name="time">中文: 当前仿真时间（秒）。English: Current simulation time (seconds).</param>
        public void Simulate(ActRuntimePlayer target, float time)
        {
            if (!IsReady) return;
            if (lastTime < start || lastTime > start + length)
            {
                if (time >= start && time <= start + length)
                {
                    OnStart(target);
                    DoAction(target, time);
                }
            }
            else
            {
                if (time < start || time > start + length)
                {
                    DoAction(target, time < start ? start : start + length);
                    OnEnd(target);
                }
                else
                {
                    DoAction(target, time);
                }
            }
            lastTime = time;
        }

        /// <summary>
        /// 中文: 编辑器中用于显示的颜色。
        /// English: Color used for display in editor.
        /// </summary>
        public abstract Color editorColor { get; }

        /// <summary>
        /// 中文: 编辑器中显示的名称。
        /// English: Name displayed in the editor.
        /// </summary>
        public abstract string editorName { get; }

        /// <summary>
        /// 中文: 片段是否已准备就绪（例如所需资源已加载）。
        /// English: Whether the clip is ready (e.g. required assets are loaded).
        /// </summary>
        public abstract bool IsReady { get; }

        /// <summary>
        /// 中文: ACT Asset被加载时会调用所有clipData示例的Prepare，用于加载整个ACT Asset的必要资源。
        /// English: Called when the ACT Asset is loaded to prepare necessary resources for the entire ACT Asset.
        /// </summary>
        /// <param name="target">中文: 运行时播放器目标。English: Runtime player target.</param>
        /// <param name="inEditor">中文: 是否在编辑器模式下。English: Whether running in editor mode.</param>
        public abstract void Prepare(ActRuntimePlayer target, IAssetLoader assetloader, bool inEditor);

        /// <summary>
        /// 中文: ACT Asset被销毁时，释放该片段占用的资源（例如卸载引用、清理缓存）。
        /// English: Release resources used by the clip (e.g. unload references, clear caches).
        /// </summary>
        /// <param name="target">中文: 运行时播放器目标。English: Runtime player target.</param>
        public abstract void ReleaseAsset(ActRuntimePlayer target);

        /// <summary>
        /// 中文: 会在进入片段的第一帧触发，注意：开发者需要同时处理从头部进入和从尾部进入的情况。
        /// English: Triggered on the first frame entering the clip; developers need to handle both head and tail entry cases.
        /// </summary>
        /// <param name="target">中文: 运行时播放器目标。English: Runtime player target.</param>
        protected abstract void OnStart(ActRuntimePlayer target);

        /// <summary>
        /// 中文: 片段进行时每帧的执行逻辑。
        /// English: Per-frame execution logic while the clip is active.
        /// </summary>
        /// <param name="target">中文: 运行时播放器目标。English: Runtime player target.</param>
        /// <param name="time">中文: 当前仿真时间（秒）。English: Current simulation time (seconds).</param>
        protected abstract void DoAction(ActRuntimePlayer target, float time);

        /// <summary>
        /// 中文: 会在离开片段的帧触发，注意：开发者需要同时处理从头部离开和从尾部离开的情况。
        /// English: Triggered on the frame leaving the clip; developers need to handle both head and tail exit cases.
        /// </summary>
        /// <param name="target">中文: 运行时播放器目标。English: Runtime player target.</param>
        protected abstract void OnEnd(ActRuntimePlayer target);
    }
}
